version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./app/static:/app/static
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    container_name: api
    depends_on:
      - redis
      - whisper

  whisper:
    build: 
      context: .
      dockerfile: whisper_service/Dockerfile
    volumes:
      - ./app/static:/app/static
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    container_name: whisper
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379" 